# XDG Base Directory Specification
XDG_CONFIG_HOME="$HOME/.config"
XDG_DATA_HOME="$HOME/.local/share"
XDG_STATE_HOME="$HOME/.local/state"
XDG_CACHE_HOME="$HOME/.cache"

# Tool Homes
ANDROID_USER_HOME="$HOME/.local/share/android"
GRADLE_USER_HOME="$HOME/.cache/gradle"
CARGO_HOME="$HOME/.local/share/cargo"
RUSTUP_HOME="$HOME/.local/share/rust"
NPM_CONFIG_USERCONFIG="$HOME/.config/npm/npmrc"
NPM_CONFIG_CACHE="$HOME/.cache/npm"
DOCKER_CONFIG="$HOME/.config/docker"
GOPATH="$HOME/.local/share/go"
GNUPGHOME="$HOME/.local/share/gnupg"
GIT_CONFIG_GLOBAL="$HOME/.config/git/config"

# Locale & Editor
EDITOR="micro"
LANG="en_US.UTF-8"